### ISSUE TITLE
Build ZAP alert title from template file instead of hardcoded string

### ISSUE THREAD

**Issue by egerod** [h3xstream/burp-retire-js#13]
For the ZAP plugin, can the template for the alert title be changed to use a template file, so that the design matches the description and other_info templates? 

It's currently the only of the 3 templates with can't be customized without changing the source code.

**Comment by h3xstream** [comment]
The template are "generic' and display information from the project Retire.js :  https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json

For this project, I did not intend to maintain additional descriptions.

What are you trying to customize?

If you are a Burp users : https://github.com/h3xstream/burp-retire-js/blob/master/retirejs-burp-plugin/src/main/resources/burp/vuln/description.html
If you are a ZAP users : https://github.com/h3xstream/burp-retire-js/tree/master/retirejs-zap-plugin/src/main/resources/org/zaproxy/zap/extension/retirejs

**Comment by egerod** [comment]
As part of the solution I'm working on, we prepend the title of  relevant ZAP alerts with a tag to signal developers what vulnerabilities to focus on (combined with the ZAP severity system). 
Currently we're doing this through a stand alone script, adding the tag after the alert have been created. But we would like to be able to customize a template for the title in the same manner as it's possible for description and other_info

Seeing as title its the only out of the three template (title, description, other_info) that's hard coded in the source code, we where wondering if it would be possible to move it to txt file, in the same manor as description and other_info.

**Comment by h3xstream** [comment]
If you do a PR, I will integrate it.

**Comment by h3xstream** [comment]
@egerod I will reopen if somebody is interested at implementing this.
