### ISSUE TITLE
org.zaproxy

### ISSUE THREAD

**Issue by mcgyver5** [h3xstream/burp-retire-js#14]
maven build failed because of org.zaproxy:zaproxy:jar:2.4.3 dependency.  Success when I changed artifactId to zap and version to 2.5.0

**Comment by h3xstream** [comment]
Thanks for the notification. I did not know ZAP has started to release their api on maven central. (http://search.maven.org/#search%7Cga%7C1%7Czaproxy)

The jar was previously manually installed.
