### ISSUE TITLE
Why is maven projects with packaging=pom silently not scanned?

### ISSUE THREAD

**Issue by smuda** [h3xstream/burp-retire-js#16]
Hi!
I added the com.h3xstream.retirejs:retirejs-maven-plugin to a maven project that creates a web client application and a node server application.

The scanning was really fast which made me suspicious. After looking at the source code for [RetireJsScan.java at line 114](https://github.com/h3xstream/burp-retire-js/blob/master/retirejs-maven-plugin/src/main/java/com/h3xstream/retirejs/RetireJsScan.java#L114) the scan is discarded if the packaging is set to "pom". It's logged at debug level which means it'll not show for normal usage.

To me it seems more appropriate to log at info but more importantly, why should scanning not be done when packaging is set to pom?

**Comment by h3xstream** [comment]
pom project are use for project without source code. Usually a project that contains sub-modules.

```
project-parent
\_ module 1
\_ module 2
```
For example if the previous structure, only module 1 and module 2 would contains resources and source directory.

I think that scanning all projects would have minimal risk of duplicate. (**duplicate in module 1 and project-parent**)

If you want to push a PR, I am interested.

**Comment by h3xstream** [comment]
I end up removing the parameter you added. I was simply a bug to ignore pom projects.

**Comment by h3xstream** [comment]
FYI : I am starting to look at the integration of RetireJs in this project -> https://github.com/h3xstream/maven-security-versions

Since this maven extension has HTML reporting already and I want to work on featurea that will benefit both project (like Jenkins integration), it seems like a logical step forward.
