### ISSUE TITLE
Updating Vulnerability Database

### ISSUE THREAD

**Issue by dvolvox** [h3xstream/burp-retire-js#2]
Does the plugin for burp updates itself to find new vulnerabilities? 

btw ~ nice plugin, thanks!

**Comment by eoftedal** [comment]
Would it be possible to cache the last downloaded version, and use that in case of connection problems. So path would be:
- Download
- Fallback to previously downloaded version on connection problems
- Fallback to bundled version if no previously downloaded version

**Comment by h3xstream** [comment]
@eoftedal : I would definitely be a great addition. I just create #4.
