### ISSUE TITLE
Passive scan doesn't pick it up

### ISSUE THREAD

**Issue by irsdl** [h3xstream/burp-retire-js#25]
When I right click and choose the Passive Scan on a vulnerable JS file, retire.js does not pickup the vulnerable JS. When I send the same JS for Active Scan it works fine.

My setting in scanner looks like this:
![image](https://user-images.githubusercontent.com/1798313/28215456-ff739f5a-68a5-11e7-8113-ea144930b543.png)

There is no debug message regarding the JS file when I select it for passive scanning in Extender>Retir.js>Output. Therefore, it seems it has not been triggered.

**Comment by h3xstream** [comment]
**Static Code Analaysis** (in the screenshot) is most likely the analysis of JavaScript content to find DOM XSS and other custom vulnerabilities. This component is built-in and not linked to RetireJs.

Do you have any specific test case to reproduce the bug?

**Comment by irsdl** [comment]
Here is the scenario I had:
too many JS files from different domains (URLs). I needed to know which ones are outdated so I added .* to the scope, I opened them one by one in browser to go through burp (without caching), then I selected them for passive scan but retire.js was not triggered. 
I disabled all the scans from active scan settings then again I selected all the JS files and selected the active scan; this time retire.js was triggered and found the vulnerable ones.
Given the fact that retire.js only needs to read the js file contents, shouldn't it be triggered using passive scan?

**Comment by h3xstream** [comment]
@irsdl Yes. Only passive scan analysis is used.

My guess is that the active scan might decide to request page that where not yet visited and therefore discovering new JS.
It may also be scripts cached by the browser and that are "forced" to be reload during the active scan.
(Those are only hypothesis.)

**Comment by irsdl** [comment]
@h3xstream does it work for you if you send a JS for passive scan? does it trigger the retire.js? it didn't for me :(

**Comment by h3xstream** [comment]
If you have sample JS or URL, let me know.

**Comment by irsdl** [comment]
The only problem is that I cannot share my targets unless they are a CDN or
something. Will let you know when I face this gain later on. Test case
should be easy though:

siteA.com/test.html -> uses siteB.com/vuln.js
In this case it does not detect the issue for siteA especially if siteB is
outside of the scope.

**Comment by h3xstream** [comment]
Passive scan should be run even if the the site is out of scope.

`siteA.com/test.html -> uses siteB.com/vuln.js` will only be found if the URL has a recognize pattern. But it should be reported on siteB.com.

**Comment by h3xstream** [comment]
In the specific case of **URL** regex being match it will rise an issue on both domain.

![RetireJS Burp preview](https://raw.githubusercontent.com/h3xstream/burp-retire-js/gh-pages/screenshots/screenshot_burp_plugin_animate.gif)
