### ISSUE TITLE
Updating DB via upstream proxy

### ISSUE THREAD

**Issue by Hipapheralkus** [h3xstream/burp-retire-js#27]
Hi,
Correct me if I'm wrong, but it appears you are loading new vulnerability DB directly, and "ignoring" the upstream proxy setup in Burp. Since my Burp instance does not have direct internet connection, I set up upstream proxy in Burp for raw.githubusercontent.com via proxy, but I'm still getting UnknownHostException.
Would it be possible to route traffic through the upstream proxy instead?
Thanks

**Comment by h3xstream** [comment]
Make sense!
Do you have an example of how to receive those settings?

**Comment by luh2** [comment]
It's not a setting you get, but use a different function. From [Your Recipe for BApp Store Success](http://blog.portswigger.net/2018/01/)

> 7) Use Burp Networking
> When making an HTTP request - to the target, or otherwise - it's preferable to use Burp's makeHttpRequest, instead of libraries like java.net.URL. This sends the request through the Burp core, so settings like upstream proxies and session handling rules will be obeyed. Many users are on a corporate network that only allows Internet access through a proxy. In addition, avoid performing any communication to the target from within doPassiveScan.

**Comment by h3xstream** [comment]
I have pushed an enhancement and test it.
Let me know if it works on your side. @Hipapheralkus
