### ISSUE TITLE
Confusion and repoUrl issue between 2.2.0 and 3.0.0

### ISSUE THREAD

**Issue by stevespringett** [h3xstream/burp-retire-js#28]
First off, thank you for making the Retirejs maven plugin. I've been using it is all my recent projects.

I've been using 2.2.0 with much success. I recently upgraded to 3.0.0 and suddenly it doesn't know the default retireJsRepoUrl and I have to specify it. When executing the plugin, I get a message back saying that it's empty or null. It seems to ignore the default value.

Although 3.0.0 appears to be the latest artifact in Maven central, the source in this repo version is at 2.3.0-SNAPSHOT. So I'm a bit confused on what is the latest release of the plugin and what version is recommended to be used.

```xml
<dependency>
    <groupId>com.h3xstream.retirejs</groupId>
    <artifactId>retirejs-maven-plugin</artifactId>
    <version>3.0.0</version>
</dependency>
```

For the time being, I've moved back to using 2.2.0 from Maven Central.

**Comment by stevespringett** [comment]
Correction. 2.1.0 is the version that works flawlessly. 2.2.0 also has the issue with retireJsRepoUrl.

**Comment by h3xstream** [comment]
I have moved the default value handling in the code rather than in the Maven plugin annotation. https://github.com/h3xstream/burp-retire-js/blob/master/retirejs-maven-plugin/src/main/java/com/h3xstream/retirejs/RetireJsScan.java#L111

I will do a release soon but you can test it already.

**Comment by h3xstream** [comment]
I finally found some time to do a new release for the Maven plugin : 
http://repo1.maven.org/maven2/com/h3xstream/retirejs/retirejs-root-pom/

The repo will soon change to `3.0.2-SNAPSHOT`.

**Comment by stevespringett** [comment]
Awesome work @h3xstream
