### ISSUE TITLE
LGPL license considerations

### ISSUE THREAD

**Issue by stevespringett** [h3xstream/burp-retire-js#29]
Hello, I'm wanting to use the retirejs-core library in an open source application (Apache 2.0 license) and there is legitimate fear that if I do, many orgs will refuse to use the parent application due to the use of a LGPL licensed component. Use of anything GPL/LGPL is typically banned in many organizations.

As of now, I have two choices. I can 1) reimplement the parts of the core that I need in a new library that is licensed under an Apache 2.0 compatible license, or 2) I can ask you to reconsider the use of LGPL in favor for a more friendly license.

So first step is to see if you'll reconsider licensing retirejs-core under the Apache 2.0 (or MIT) license. Please let me know either way.

**Comment by h3xstream** [comment]
Apache 2.0 would make sense as Retire.JS is licensed under Apache.

I am planning to do a release by the end of the year. It will atleast include #26. It would be a good moment to switch license.

**Comment by h3xstream** [comment]
Acknowledgement to the previous developers. The license was changed from LGPL to Apache 2.0.
@smuda @3colezlaw @thc202 @mike-smith-portswigger @matchai @eoftedal

Sorry for the spam.

**Comment by stboiss** [comment]
@h3xstream when do you think released with this new license ?
