### ISSUE TITLE
Do not include file name in issue title

### ISSUE THREAD

**Issue by franklinyu** [h3xstream/burp-retire-js#36]
Burp seems to merge issues with same title. Current issue structure:

```text
The file 'jquery.min.js' includes a vulnerable version of the library 'jquery'
 - /static/js/jquery.min.js
 - /static/js/jquery.min.js
The file 'index.html' includes a vulnerable version of the library 'jquery'
 - /static/html/index.html
 - /static/html/index.html
The file 'login.html' includes a vulnerable version of the library 'jquery'
 - /static/html/login.html
 - /static/html/login.html
The file 'items.html' includes a vulnerable version of the library 'jquery'
 - /static/html/items.html
 - /static/html/items.html
```

Which is multiple groups of the same issue. It would be more tidy to simply say

```text
Vulnerable version of the library 'jquery' detected
 - /static/js/jquery.min.js
 - /static/js/jquery.min.js
 - /static/html/index.html
 - /static/html/index.html
 - /static/html/login.html
 - /static/html/login.html
 - /static/html/items.html
 - /static/html/items.html
```

Because the file name would be available anyway.

**Comment by h3xstream** [comment]
This PR https://github.com/h3xstream/burp-retire-js/pull/35 will fix this.
Stay tune.

**Comment by h3xstream** [comment]
Update for the Bapp store was requested. It should update automatically your plugin soon.

**Comment by franklinyu** [comment]
I think the `ScreenVersion` in `BappManifest.bmf` should also be updated?

**Comment by franklinyu** [comment]
Did I miss something? The updated version is still not available on BApp Store. [The store page](https://portswigger.net/bappstore/36238b534a78494db9bf2d03f112265c) suggests that last update was in March.
