### ISSUE TITLE
False Positives with embedded JavaScript Libraries

### ISSUE THREAD

**Issue by soffensive** [h3xstream/burp-retire-js#38]
The current implementation does not use the DOM representation of websites but rather the whole HTTP response.
As a result, any embedded JavaScript file embedded within a comment will yield a false positive by the retireJS burp plugin 
Example:

`<!--  --> <script src=jquery-vuln.js/> -->`

https://github.com/h3xstream/burp-retire-js/blob/c0a61db422aea8745281f9d743ed18c8ad1f66c4/retirejs-core/src/main/java/com/h3xstream/retirejs/repo/ScannerFacade.java#L63

I can imagine two possible ways to fix it:

1) (My preferred solution): Use a library for proper DOM parsing rather than parsing the HTTP response line-by-line and match strings (e.g. jsoup).

2) Check manually whether the detected <script> tag is embedded within a comment section.
Pseudocode:
`commentEnd = findFromBackwards(begin=0, end=scriptoffset, "-->");`
`commentBegin = findFromBackwards(begin=0, end=scriptoffset, "!--");`
`if commentBegin > commentEnd:  
//Abort, we are inside a comment`

Due to my limited Java skills and time constraints I have not prepared a pull request yet ;)

If this behaviour is intended, the plugin should at least make explicit that the vulnerability is theoretical only.

**Comment by h3xstream** [comment]
False positive is not a big problem at the moment.
I don't think JSoup would scale under large number of requests.

**Comment by h3xstream** [comment]
I will leave this issue open and tag it as **wontfix**. Just in case many people encounter a large number of commented scripts.
