### ISSUE TITLE
 " org.apache.maven.wagon.TransferFailedException: raw.githubusercontent.com " 

### ISSUE THREAD

**Issue by codingmak** [h3xstream/burp-retire-js#45]
There is an issue with running mvn -DrepoURL=localfile com.h3xstream.retirejs:retirejs-mave-plugin:scan offline.

**Comment by h3xstream** [comment]
Can you provide the output of maven `mvn -X ...`

**Comment by h3xstream** [comment]
I supposed that your local file path starts with "file://". I could had a condition to avoid using the Wagon proxy config here : 

https://github.com/h3xstream/burp-retire-js/blob/4b874d4515d4fab4617eaa5b4dacb04f4a7bfe48/retirejs-maven-plugin/src/main/java/com/h3xstream/retirejs/MavenDownloader.java#L37-L49

**Comment by codingmak** [comment]
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: C:\Users\Alex\Desktop\apache-maven-3.5.3\bin\..
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jre1.8.0_171
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.annotation.* < plexus.core
[DEBUG]   Imported: javax.annotation.security.* < plexus.core
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.fusesource.jansi.* < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from C:\Users\Alex\Desktop\apache-maven-3.5.3\bin\..\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\Alex\.m2\settings.xml
[DEBUG] Reading global toolchains from C:\Users\Alex\Desktop\apache-maven-3.5.3\bin\..\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\Alex\.m2\toolchains.xml
[DEBUG] Using local repository at C:\Users\Alex\.m2\repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\Users\Alex\.m2\repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project SampleJerseyApp:SampleJerseyApp:war:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging war from ClassRealm[plexus.core, parent: null]
[DEBUG] Skipped remote request for com.h3xstream.retirejs:retirejs-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for com.h3xstream.retirejs:retirejs-maven-plugin to 3.0.2 from repository C:\Users\Alex\.m2\repository (enhanced)
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: SampleJerseyApp:SampleJerseyApp:war:1.0-SNAPSHOT
[DEBUG] Tasks:   [com.h3xstream.retirejs:retirejs-maven-plugin:scan]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO] 
[INFO] ------------------< SampleJerseyApp:SampleJerseyApp >-------------------
[INFO] Building SampleJerseyApp 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[DEBUG] Skipped remote request for com.h3xstream.retirejs:retirejs-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for com.h3xstream.retirejs:retirejs-maven-plugin to 3.0.2 from repository C:\Users\Alex\.m2\repository (enhanced)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       SampleJerseyApp:SampleJerseyApp:1.0-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2:scan (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <breakOnFailure>${retireJsBreakOnFailure}</breakOnFailure>
  <project>${project}</project>
  <repoUrl>${retireJsRepoUrl}</repoUrl>
  <webAppDirectory default-value="${basedir}/src/main/webapp">${retireWebAppDir}</webAppDirectory>
</configuration>
[DEBUG] =======================================================================
[INFO] 
[INFO] --- retirejs-maven-plugin:3.0.2:scan (default-cli) @ SampleJerseyApp ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=913748, ConflictMarker.markTime=314845, ConflictMarker.nodeCount=78, ConflictIdSorter.graphTime=500575, ConflictIdSorter.topsortTime=348284, ConflictIdSorter.conflictIdCount=38, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=6066491, ConflictResolver.conflictItemCount=74, DefaultDependencyCollector.collectTime=156400522, DefaultDependencyCollector.transformTime=9828748}
[DEBUG] com.h3xstream.retirejs:retirejs-maven-plugin:jar:3.0.2:
[DEBUG]    com.h3xstream.retirejs:retirejs-core:jar:3.0.2:compile
[DEBUG]       org.json:json:jar:20140107:compile
[DEBUG]       com.esotericsoftware:minlog:jar:1.3:compile
[DEBUG]       com.github.spullara.mustache.java:compiler:jar:0.8.17:compile
[DEBUG]          com.google.guava:guava:jar:16.0.1:compile
[DEBUG]    commons-io:commons-io:jar:2.4:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.2.1:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.2.1:compile
[DEBUG]          org.codehaus.plexus:plexus-interpolation:jar:1.11:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.2.1:compile
[DEBUG]       org.slf4j:slf4j-jdk14:jar:1.5.6:runtime
[DEBUG]          org.slf4j:slf4j-api:jar:1.5.6:runtime
[DEBUG]       org.slf4j:jcl-over-slf4j:jar:1.5.6:runtime
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:2.2.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-sink-api:jar:1.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-logging-api:jar:1.1:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-model:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:2.2.1:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          junit:junit:jar:3.8.1:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-project:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-plugin-registry:jar:2.2.1:compile
[DEBUG]       commons-cli:commons-cli:jar:1.2:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.2.1:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[DEBUG]          backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.2.1:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.5.15:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG] Created new class realm plugin>com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2
[DEBUG] Importing foreign packages into class realm plugin>com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2
[DEBUG]   Included: com.h3xstream.retirejs:retirejs-maven-plugin:jar:3.0.2
[DEBUG]   Included: com.h3xstream.retirejs:retirejs-core:jar:3.0.2
[DEBUG]   Included: org.json:json:jar:20140107
[DEBUG]   Included: com.esotericsoftware:minlog:jar:1.3
[DEBUG]   Included: com.github.spullara.mustache.java:compiler:jar:0.8.17
[DEBUG]   Included: com.google.guava:guava:jar:16.0.1
[DEBUG]   Included: commons-io:commons-io:jar:2.4
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.11
[DEBUG]   Included: org.slf4j:slf4j-jdk14:jar:1.5.6
[DEBUG]   Included: org.slf4j:jcl-over-slf4j:jar:1.5.6
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.2.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-logging-api:jar:1.1
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: commons-cli:commons-cli:jar:1.2
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: backport-util-concurrent:backport-util-concurrent:jar:3.1
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.15
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG] Configuring mojo com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2:scan from plugin realm ClassRealm[plugin>com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2, parent: sun.misc.Launcher$AppClassLoader@647e05]
[DEBUG] Configuring mojo 'com.h3xstream.retirejs:retirejs-maven-plugin:3.0.2:scan' with basic configurator -->
[DEBUG]   (f) project = MavenProject: SampleJerseyApp:SampleJerseyApp:1.0-SNAPSHOT @ C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\pom.xml
[DEBUG]   (f) webAppDirectory = C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp
[DEBUG] -- end configuration --
[DEBUG] Using default URL: https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json
[DEBUG] Caching Retire.js latest repository
[DEBUG] Loading the latest Retire.js repository
[DEBUG] 31 loaded library.
[INFO] Scanning directory: C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp
[DEBUG] Scanning C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js
[DEBUG] Analysing URI: "C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js"
[DEBUG] It took ~0 sec. (1 ms) to scan
[DEBUG] No path matching the script (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js)
[DEBUG] Analysing filename: ":\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js"
[DEBUG] It took ~0 sec. (0 ms) to scan
[DEBUG] No filename matching the script (:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js)
[DEBUG] No hash matching 2b6fe888fe3389106a2d87f26ab29af1ee0c44f0 (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js)
[DEBUG] Analysing the content: "var myApp = angular.[..]"
[DEBUG] It took ~0 sec. (10 ms) to scan
[DEBUG] No content matching the script "C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\app.js"
[DEBUG] Scanning C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js
[DEBUG] Analysing URI: "C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js"
[DEBUG] It took ~0 sec. (0 ms) to scan
[DEBUG] No path matching the script (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js)
[DEBUG] Analysing filename: ":\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js"
[DEBUG] It took ~0 sec. (1 ms) to scan
[DEBUG] No filename matching the script (:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js)
[DEBUG] No hash matching 8c639912ccd43078865578e598607d1b847c2373 (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js)
[DEBUG] Analysing the content: "/*! * Bootstrap v3.[..]"
[DEBUG] Pattern match "\* Bootstrap v([0-9][0-9.a-z_\\\\-]+)" !
[DEBUG] Identify the library bootstrap (version:3.2.0)
[DEBUG] Vulnerability found: bootstrap below 4.0.0-beta.2
[DEBUG] It took ~0 sec. (58 ms) to scan
[WARNING] bootstrap.js contains a vulnerable JavaScript library.
[INFO] Path: C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.js
[INFO] bootstrap version 3.2.0 is vulnerable.
[INFO] + https://github.com/twbs/bootstrap/issues/20184
[DEBUG] Scanning C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js
[DEBUG] Analysing URI: "C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js"
[DEBUG] It took ~0 sec. (0 ms) to scan
[DEBUG] No path matching the script (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js)
[DEBUG] Analysing filename: ":\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js"
[DEBUG] It took ~0 sec. (0 ms) to scan
[DEBUG] No filename matching the script (:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js)
[DEBUG] No hash matching 26908395e7a9a4eab607d80aa50a81d65f3017cb (C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js)
[DEBUG] Analysing the content: "/*! * Bootstrap v3.[..]"
[DEBUG] Pattern match "\* Bootstrap v([0-9][0-9.a-z_\\\\-]+)" !
[DEBUG] Identify the library bootstrap (version:3.2.0)
[DEBUG] Vulnerability found: bootstrap below 4.0.0-beta.2
[DEBUG] It took ~0 sec. (31 ms) to scan
[WARNING] bootstrap.min.js contains a vulnerable JavaScript library.
[INFO] Path: C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\webapp\bootstrap\js\bootstrap.min.js
[INFO] bootstrap version 3.2.0 is vulnerable.
[INFO] + https://github.com/twbs/bootstrap/issues/20184
[DEBUG] Scanning directory: C:\Users\Alex\Desktop\burp-retire-js-4ade281a378126269b6be70a38c5f2ceaad0121c\sample-jersey-webapp-master\sample-jersey-webapp-master\src\main\java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.193 s
[INFO] Finished at: 2018-07-02T15:09:47-04:00
[INFO] ------------------------------------------------------------------------

**Comment by codingmak** [comment]
Is there a way to get maven to point to a local json file when offline for example instead of this default repo: 

 public static final String REPO_URL = "https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json";

**Comment by h3xstream** [comment]
I have a enhancement that goes as follow:

`mvn com.h3xstream.retirejs:retirejs-maven-plugin:scan` : Sync with the retirejs github repo

`mvnDebug com.h3xstream.retirejs:retirejs-maven-plugin:scan -DretireJsRepoUrl=https://gist.githubusercontent.com/h3xstream/c901cd4f83c3e8dd54474725efb5b77c/raw/121626d98e85c8946f29a1799007ceaef1e5aa84/repo-jquery-only.json` : Sync with a specific URL where the host can be different than github.com.

`mvn com.h3xstream.retirejs:retirejs-maven-plugin:scan -DretireJsRepoUrl=file:C:/code/repo-jquery-only.json` : Use a local version of the repo.

**Comment by h3xstream** [comment]
cd6a27573e82668f167201eec22de490dbbf0a05
