### ISSUE TITLE
Burp plugin versioning

### ISSUE THREAD

**Issue by Hipapheralkus** [h3xstream/burp-retire-js#46]
I'm very confused which is the newest version, and which one should be used... In your repository, you have link to `https://raw.githubusercontent.com/h3xstream/burp-retire-js/gh-pages/releases/burp/burp-retire-js-3.0.1.jar` - **3.0.1**
In your pom.xml file `https://github.com/h3xstream/burp-retire-js/blob/master/retirejs-burp-plugin/pom.xml` you mention version **3.0.2**
When I check the BappStore, there is version **2.3.1**: `https://portswigger.net/bappstore/36238b534a78494db9bf2d03f112265c`
And then when I download the actual .bapp file, open it in 7-zip -> `Retire.js_v2.3.1.bapp\retirejs-burp-plugin\target\burp-retire-js-3.jar` there is version **3**.
Would it be possible to somehow standardize and sync all the possible values, so that we know which is the newest version?
Thanks

**Comment by h3xstream** [comment]
Good point.

- I verified the Bapp package and it is 3.0.2. The error is in the description. I will contact burp support.

```
#Generated by Maven
#Fri Jun 29 14:47:04 UTC 2018
version=3.0.2
groupId=com.h3xstream.retirejs
artifactId=retirejs-core
```

- I will update the download link in the README.md (Which is one version behind.)
