### ISSUE TITLE
burp extension response marker grabs too much content

### ISSUE THREAD

**Issue by tmendo** [h3xstream/burp-retire-js#48]
Retire.js correctly detects this JS (https://wallet.pt/assets/common/js/jquery-ui.js) as being outdated.

However, the markers on the response seem to suffer from a greedy regex.
The marker ends with `y.prototype,{destroy:function(){b.ui.dialog`, so probably its detecting the last `ui.dialog` from the file.

I can try to fix this and submit a PR, if this was not the intended behaviour. 

<img width="896" alt="screen shot 2018-07-13 at 13 19 39" src="https://user-images.githubusercontent.com/1278447/42691320-6b2c8f1e-869f-11e8-86ca-99204fc8a8ed.png">

Bapp store version, 2.3.1

**Comment by h3xstream** [comment]
I assumed this is fix by #47
