### ISSUE TITLE
Incompatible/Buggy Behaviour with BurpSuite >=2.0.0.x

### ISSUE THREAD

**Issue by nksCH** [h3xstream/burp-retire-js#51]
I installed the plugin via BApp Store, get expected output after activating the plugin:
```
== Retire.js plugin ==
Passive scan rules to detect vulnerable Javascript libraries
 - Github : https://github.com/h3xstream/burp-retire-js

== License ==
Retire.js repository is release under Apache License v2.
Retire.js Burp plugin is release under LGPL.

00:00  INFO: Caching Retire.js latest repository
00:00  INFO: Loading the latest Retire.js repository

```

However, when requesting the test cases e.g.:
https://raw.githubusercontent.com/h3xstream/burp-retire-js/master/test-samples/jquery-1.6.2.js

There is no new issue in the target view. No error in output, Dashboard Event Log, and error log.

Expected:
New issue in target view or error triggered.

**Comment by ninijay** [comment]
Somehow, when debugging the `scanJavaScript` method in `BurpExtender.java` (via IDE==IntelliJ) it seems to work:
![image](https://user-images.githubusercontent.com/6756364/47796309-5e922f80-dd24-11e8-840a-acd3fc626961.png)
But when building the .jar and using it in Burp >= 2.0.0.x or running the Extension from within an IDE it doesn't seem to work:
![image](https://user-images.githubusercontent.com/6756364/47796431-9f8a4400-dd24-11e8-837c-fc18ad56d02b.png)

Maybe there are some timing/ thread syncing issues?

@PortSwigger may have changed something there.

**Comment by h3xstream** [comment]
It might have been a bug in Burp 2. I think this was fixed on Burp side.

Tested on the latest version:
![test burp 2](https://user-images.githubusercontent.com/593130/70542329-8adacb00-1b36-11ea-8957-0c3bb1e8e271.png)

**Comment by h3xstream** [comment]
Let me know if this is still happening.
