### ISSUE TITLE
StackOverflowError in `findByFileContent`

### ISSUE THREAD

**Issue by jeremylong** [h3xstream/burp-retire-js#54]
I am starting here - but this may need to be raised against the RetireJs repo; the original report is against [dependency-check #1969](https://github.com/jeremylong/DependencyCheck/issues/1969).

When using the core library to scan [jquery-ui-1.6rc6-customized.js](https://github.com/jeremylong/DependencyCheck/files/3252205/jquery-ui-1.6rc6-customized.js.zip) a StackOverflowError occurs in `com.h3xstream.retirejs.repo.VulnerabilitiesRepository#findByFileContent(String)`. The error specifically occurs when scanning for `jquery-ui-dialog` using the regex:

```
/\*!?[\n *]+jQuery UI ([0-9][0-9.a-z_\\\\-]+)(.*\n)*.*\.ui\.dialog
```
Originally retrieved from: https://github.com/RetireJS/retire.js/blob/cde69c04e63b65c1cba235efad01e904f28f4bd5/repository/jsrepository.json#L260

As with most regex issues - the stack trace is super helpful:

```
java.lang.StackOverflowError: null
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4656)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4272)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
        ...
```

**Comment by jeremylong** [comment]
This can be solved by increasing the stack size:
```
export JAVA_OPTS="-Xss5000m -Xms1024m -Xmx7168m"
```
I have updated the error reporting in dependency-check to let users know how to resolve this issue.

**Comment by h3xstream** [comment]
I think it would be good to at least catch the StackOverflowError and continue to the next Regex.

**Comment by jeremylong** [comment]
One of the things we did in dependency-check was update the error message to indicate how one can resolve the issue.  See https://github.com/jeremylong/DependencyCheck/blob/cc387b6d039e19d004866d4c67178d631c405693/core/src/main/java/org/owasp/dependencycheck/analyzer/RetireJsAnalyzer.java#L235-L241

I agree, continuing on would be good, but an warning/log message would be good as well.
