### ISSUE TITLE
Integration with ZAP-CLI

### ISSUE THREAD

**Issue by wheelq** [h3xstream/burp-retire-js#55]
Is there any way of integrating this into ZAP-cli ?

**Comment by h3xstream** [comment]
Running active or passive scan should trigger potential issue. You just need to verify that the plugin is enable.

**Comment by wheelq** [comment]
What?😂

**Comment by h3xstream** [comment]
Have you tried `active-scan` or `quick-scan` command from ZAP-cli ?
Let me know what you have tried so far.

**Comment by wheelq** [comment]
I would but I do not know how to integrate this plugin with zap-cli

**Comment by h3xstream** [comment]
Likely a question that should be ask to the project ZAP-CLI..

If their is a bug, let me know what was tried and some detail on what was missing or broken.
