### ISSUE TITLE
RetireJS update

### ISSUE THREAD

**Issue by PierrickV** [h3xstream/burp-retire-js#59]
Hi,

Can you please update your plugin to the latest version of Retire.js ? : D

See https://github.com/RetireJS/retire.js/commits/master & https://github.com/RetireJS/retire.js/tags

Regards

Edit: I use it every day and I love it, thank you for your work ! <3

**Comment by h3xstream** [comment]
The plugin will fetch the latest version of Retire.js repository as soon as you have internet access.
This is why we don't update the local copy all the time.

**Comment by PierrickV** [comment]
Ok thank you for your kind answer ! =)
