### ISSUE TITLE
ZAP 2.4.0 Compatibility

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/burp-retire-js#7]
Issue from ZAP project : https://github.com/zaproxy/zaproxy/issues/1705

**Comment by psiinon** [comment]
Are you planning on releasing a new version of the add-on for this?
The one linked from https://github.com/h3xstream/burp-retire-js will not load in any of the recent versions of ZAP.

**Comment by h3xstream** [comment]
Yes I will. I was hoping to do this last week. :S

@psiinon Would you like to be notify when I all my plugins are updated for this version fix? I could notify you when they are "market-ready".

**Comment by psiinon** [comment]
That would be great :)
Very happy to publicise this on various ZAP channels. And as discussed before, would love to include this in the Marketplace as long as it doesnt make external calls.

**Comment by h3xstream** [comment]
The plugin was package and test for ZAP 2.4.3.
@psiinon I will send you an email today (mailing list) with all the info of this plugin and other plugins.

**Comment by psiinon** [comment]
Great, thanks
