### ISSUE TITLE
retirejs-maven-plugin:2.1.0 does not appear to use maven proxy settings:

### ISSUE THREAD

**Issue by skotfred** [h3xstream/burp-retire-js#8]
Process works as expected while not connected to corporate network, but fails to load repository when proxy is to be used.

Console output:
```
[INFO] --- retirejs-maven-plugin:2.1.0:scan (scanProject) @ Demo ---
[ERROR] Exception while loading the repository (Most likely unable to access the internet) java.net.UnknownHostException: raw.githubusercontent.com
```

**pom.xml:**
```xml
<plugin>
	<groupId>com.h3xstream.retirejs</groupId>
	<artifactId>retirejs-maven-plugin</artifactId>
	<version>2.1.0</version>
	<executions>
		<execution>
			<id>scanProjectJS</id>
			<phase>install</phase>
			<goals>
				<goal>scan</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**settings.xml (some values masked for security):**
```xml
<proxies>
 <proxy>
   <id>INTERNALDOMAINproxy-http</id>
   <active>true</active>
   <protocol>http</protocol>
   <host>proxy.INTERNALDOMAIN.com</host>
   <port>80</port>
   <username>INTERNALDOMAIN\userid</username>
   <password>************</password>
   <nonProxyHosts>localhost,127.0.0.1,*.INTERNALDOMAIN.com</nonProxyHosts>
 </proxy>
</proxies>
```

**Comment by skotfred** [comment]
Updated config to escape &gt; and &lt; characters for readabilty.

**Comment by h3xstream** [comment]
Ok. It should not be to hard to implement. I remember using the [Wagon HTTP api](https://maven.apache.org/components/wagon/wagon-providers/wagon-http/) which support proxy configuration

I will try to implement this before JavaOne (end of October).

**Comment by h3xstream** [comment]
Release to Maven repository will be done ASAP.

**Comment by skotfred** [comment]
This update still does not show in Maven Central.  Most current version there remains as version 2.1.0  (08-Jun-2015)
