### ISSUE TITLE
Hardcoded Rules URL

### ISSUE THREAD

**Issue by nop-sledding-with-my-snowshoes** [h3xstream/burp-retire-js#9]
Could you make the option for the rules that the plugin will fetch from github, to be able to assigned from an alternative location?  I typically work in closed networks without internet access and would like the ability to fetch from my own URL or local file store, without having to recompile the plugin and lose the updates functionality through the BApp store.

**Comment by h3xstream** [comment]
I am planning to make a few updates to the plugin in the next weeks including #4.
The repository (basically the big json file) will be cache locally.
You could manually overwrite it.

**Comment by nopnopnoppopopret** [comment]
Yes, ideally I would like something like this.  I understand if that takes too much time, but I want to maintain updates from the BApp store, without manually changing it for myself.  If I were to set the json repo locally now, would the plugin see it?  Also, where would it be stored?
![burp](https://cloud.githubusercontent.com/assets/573886/11900468/0fdaddfa-a574-11e5-9b7c-0051c54e82d8.PNG)

**Comment by nopnopnoppopopret** [comment]
Have you looked into this?

**Comment by h3xstream** [comment]
You will be able to change/update manually the repository at : `$USER/.retirejs/jsrepository.json`

This is not exactly a configuration but you should be able to control the repository you wanted.

**Comment by bsk32** [comment]
how can  retire.js work with out internet
